### ISSUE TITLE
Introduce language level estimation test

### ISSUE THREAD

**Issue by kirillidk** [spbu-math-cs-mse/LingvoFriend#21]

**Comment by sharkov63** [comment]
This in a very important feature for Sprint 3. We will need additional long call with Victoria to understand the feature and develop a formal requirement.

**Comment by sharkov63** [comment]
Based on discussion 13.11.2023 with stakeholders. The language estimation test is done entirely by LLM with certain prompts. Victoria provided a sample of these prompts, and we are waiting for more. Our task would be to parse LLM output to get an enum value of CEFR A1-C2. This might be a problem, because LLM can output any garbage, but it is to be seen yet.
